// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0OYlgJIO-pVn3yG7oGKbKcD3S10wzECM',
    appId: '1:795363549804:web:0e4c4b75d27703e22cee49',
    messagingSenderId: '795363549804',
    projectId: 'fureverflutter',
    authDomain: 'fureverflutter.firebaseapp.com',
    storageBucket: 'fureverflutter.firebasestorage.app',
    measurementId: 'G-5XKJ6B78D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHCrTIf4HWUVBywaJEeEFcOAd9iBdTuGg',
    appId: '1:795363549804:android:308990f31a574c6a2cee49',
    messagingSenderId: '795363549804',
    projectId: 'fureverflutter',
    storageBucket: 'fureverflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgivzFyYpp2WekTGcLKnirRDQFansqlBU',
    appId: '1:795363549804:ios:f11a014ebc1a902b2cee49',
    messagingSenderId: '795363549804',
    projectId: 'fureverflutter',
    storageBucket: 'fureverflutter.firebasestorage.app',
    iosBundleId: 'com.example.fureverflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgivzFyYpp2WekTGcLKnirRDQFansqlBU',
    appId: '1:795363549804:ios:f11a014ebc1a902b2cee49',
    messagingSenderId: '795363549804',
    projectId: 'fureverflutter',
    storageBucket: 'fureverflutter.firebasestorage.app',
    iosBundleId: 'com.example.fureverflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0OYlgJIO-pVn3yG7oGKbKcD3S10wzECM',
    appId: '1:795363549804:web:7eb8bbf69b1917f72cee49',
    messagingSenderId: '795363549804',
    projectId: 'fureverflutter',
    authDomain: 'fureverflutter.firebaseapp.com',
    storageBucket: 'fureverflutter.firebasestorage.app',
    measurementId: 'G-MEMEV67PNY',
  );
}
